name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  provider: ^6.1.5+1
  go_router: ^16.2.1
  image_picker: ^1.1.2
  geolocator: ^12.0.0
  intl: ^0.19.0
  google_fonts: ^6.3.1
  font_awesome_flutter: ^10.9.1
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.5.0
  build_runner: ^2.7.0

flutter:
  uses-material-design: true
